-- AlterEnum
ALTER TYPE "LegalForm" ADD VALUE 'EI';
ALTER TYPE "LegalForm" ADD VALUE 'SCS';
ALTER TYPE "LegalForm" ADD VALUE 'SCA';
ALTER TYPE "LegalForm" ADD VALUE 'SCM';
ALTER TYPE "LegalForm" ADD VALUE 'SCP';
ALTER TYPE "LegalForm" ADD VALUE 'SCPI';
ALTER TYPE "LegalForm" ADD VALUE 'SCCV';
ALTER TYPE "LegalForm" ADD VALUE 'SELARL';
ALTER TYPE "LegalForm" ADD VALUE 'SELAS';
ALTER TYPE "LegalForm" ADD VALUE 'SPFPL';
ALTER TYPE "LegalForm" ADD VALUE 'GIE';
ALTER TYPE "LegalForm" ADD VALUE 'GFA';
