import type { User, Society, UserSociety } from "@prisma/client"
import { UserRole, InvoiceStatus, InvoiceType, RiskIndicator, LegalForm, TaxRegime, VatRegime } from "@prisma/client"

export const buildUser = (overrides?: Partial<User>): User => ({
  id: "user-1",
  name: "Test User",
  email: "test@example.com",
  emailVerified: null,
  passwordHash: "hashed",
  isActive: true,
  firstName: null,
  image: null,
  lastLoginAt: null,
  twoFactorEnabled: false,
  twoFactorSecret: null,
  twoFactorRecoveryCodes: [],
  pendingTwoFactorSecret: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
}) as User

export const buildSociety = (overrides?: Partial<Society>): Society => ({
  id: "society-1",
  name: "Ma Societe",
  siret: "12345678901234",
  legalForm: LegalForm.SCI,
  vatNumber: null,
  addressLine1: "1 rue de la Paix",
  addressLine2: null,
  city: "Paris",
  postalCode: "75001",
  country: "France",
  phone: null,
  shareCapital: null,
  signatoryName: null,
  ibanEncrypted: null,
  bicEncrypted: null,
  bankName: null,
  taxRegime: TaxRegime.IS,
  vatRegime: VatRegime.TVA,
  accountantName: null,
  accountantFirm: null,
  accountantEmail: null,
  accountantPhone: null,
  logoUrl: null,
  legalMentions: null,
  invoicePrefix: null,
  nextInvoiceNumber: 0,
  invoiceNumberYear: 0,
  isActive: true,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
} as Society)

export const buildMembership = (role: UserRole = UserRole.GESTIONNAIRE, overrides = {}): UserSociety => ({
  id: "membership-1",
  userId: "user-1",
  societyId: "society-1",
  role,
  createdAt: new Date(),
  ...overrides,
} as UserSociety)

export const buildTenantPhysique = (overrides = {}) => ({
  id: "tenant-1",
  societyId: "society-1",
  entityType: "PERSONNE_PHYSIQUE" as const,
  email: "locataire@example.com",
  firstName: "Jean",
  lastName: "Dupont",
  isActive: true,
  riskIndicator: RiskIndicator.VERT,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
})

export const buildInvoice = (overrides = {}) => ({
  id: "invoice-1",
  societyId: "society-1",
  tenantId: "tenant-1",
  leaseId: null,
  invoiceNumber: "FAC-2026-0001",
  invoiceType: InvoiceType.APPEL_LOYER,
  status: InvoiceStatus.EN_ATTENTE,
  issueDate: new Date(),
  dueDate: new Date(),
  periodStart: null,
  periodEnd: null,
  totalHT: 1000,
  totalVAT: 200,
  totalTTC: 1200,
  fileUrl: null,
  sentAt: null,
  sentBy: null,
  creditNoteForId: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
})
